"""Generate the serverless worker artifacts from your ComfyUI workflows.

Scans workflow JSONs, works out which custom-node repos and which model files they
need, and writes:
    Dockerfile             union of custom-node repos (one image runs every workflow)
    extra_model_paths.yaml the model dirs ComfyUI should read from the volume
    models_manifest.json    {local path -> volume key} for every model that exists
                            locally (consumed by upload_models.py)

A weight is only collected when its (class_type, input_key) is a real loader input
(see LOADER_INPUTS). A weight-looking string on a non-loader input — e.g. a stray
ckpt_name on UNETLoader, which only reads unet_name — is reported as IGNORED and
NOT uploaded, so a phantom field can't quietly bloat the volume.

Run from the project root:
    python runpod/worker/gen_worker.py                 # all workflows/*.json
    python runpod/worker/gen_worker.py anima_cutout_api sprite_api   # a subset
    python runpod/worker/gen_worker.py --models-dir D:/ComfyUI/models

Custom nodes are resolved with a curated map (below) first; anything unknown is
looked up in ComfyUI-Manager's published node map if --online is passed, else
reported as UNRESOLVED so you can add it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORKFLOWS = ROOT / "workflows"
HERE = Path(__file__).resolve().parent
DEFAULT_MODELS_DIR = r"C:\Users\micha\Documents\ComfyUI\models"

# Runtime GPU/PyTorch adaptation. A Docker image is built once with one torch build (cu126,
# sm_80–sm_90), but the container can land on a GPU that build can't run (e.g. Blackwell sm_120).
# We can't detect the GPU at BUILD time (no device in the builder), so we adapt at STARTUP:
# smoke-test CUDA and, only on failure, let light-the-torch auto-pick the wheel for the driver's
# CUDA version. The fast path (compatible GPU) adds one tiny tensor op — no install, no network.
_ADAPTIVE_START = r"""#!/usr/bin/env bash
# AUTO-GENERATED by gen_worker.py — adapts PyTorch to the actual GPU, then runs the base worker.
set -u
PIN="torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1"   # >=2.7.1 required by KJNodes fp16-accum probe

if python3 -c "import torch; torch.randn(8,8,device='cuda').sum().item()" >/dev/null 2>&1; then
    echo "adaptive-torch: baked $(python3 -c 'import torch;print(torch.__version__)') runs on this GPU — keeping it"
else
    cap="$(nvidia-smi --query-gpu=compute_cap,name --format=csv,noheader 2>/dev/null | head -n1)"
    echo "adaptive-torch: baked PyTorch cannot run on this GPU (${cap:-unknown}) — selecting a matching build via light-the-torch"
    # ltt auto-detects the driver's CUDA version and installs the matching wheels. Try the pinned
    # version first; if that backend has no wheel for this version, fall back to ltt's best pick.
    python3 -m light_the_torch install --upgrade $PIN \
        || python3 -m light_the_torch install --upgrade torch torchvision torchaudio \
        || echo "adaptive-torch: WARNING light-the-torch install failed; continuing with baked torch"
    python3 -c "import torch; torch.randn(8,8,device='cuda').sum().item(); print('adaptive-torch: now', torch.__version__, 'CUDA OK')" \
        || echo "adaptive-torch: WARNING CUDA still not usable after adaptation"
fi

exec /start.sh
"""

# Nodes shipped with ComfyUI itself (core + comfy_extras). Not exhaustive, but
# covers everything these workflows use; unknown nodes get resolved as custom.
CORE_NODES = {
    "CheckpointLoaderSimple", "CheckpointLoader", "CLIPTextEncode", "KSampler", "KSamplerAdvanced",
    "EmptyLatentImage", "EmptySD3LatentImage", "VAEDecode", "VAEEncode", "VAEEncodeForInpaint",
    "SaveImage", "SaveImageWithAlpha", "PreviewImage", "LoadImage", "LoadImageMask",
    "LoraLoader", "LoraLoaderModelOnly", "ConditioningConcat", "ConditioningCombine",
    "ConditioningSetArea", "ConditioningSetAreaPercentage", "ConditioningZeroOut",
    "ConditioningAverage", "FluxGuidance", "UpscaleModelLoader", "ImageUpscaleWithModel",
    "ImageScale", "ImageScaleBy", "LatentUpscale", "LatentUpscaleBy", "VAELoader",
    "CLIPSetLastLayer", "CLIPLoader", "DualCLIPLoader", "UNETLoader", "ControlNetLoader",
    "ControlNetApply", "ControlNetApplyAdvanced", "InpaintModelConditioning", "RepeatLatentBatch",
    "EmptyImage", "ImageBatch", "ImagePadForOutpaint", "LatentFromBatch", "PrimitiveNode",
    "Note", "Reroute", "GrowMask", "MaskToImage", "ImageToMask", "InvertMask", "SolidMask",
    "FeatherMask", "SetLatentNoiseMask", "CLIPVisionLoader", "CLIPVisionEncode",
    "StyleModelLoader", "StyleModelApply", "unCLIPConditioning", "PerpNeg",
    "ModelSamplingDiscrete", "ModelSamplingSD3", "ModelSamplingFlux", "ModelSamplingAuraFlow",
    "SamplerCustom",
    "SamplerCustomAdvanced", "BasicScheduler", "BasicGuider", "RandomNoise", "KSamplerSelect",
    "SplitSigmas", "SplitSigmasDenoise", "FlipSigmas",  # comfy_extras custom-sampler family (krea2 denoise split)
    "Mahiro", "RescaleCFG", "ImageCrop", "ImageInvert", "ImageBlend", "JoinImageWithAlpha",
    "SplitImageWithAlpha", "VAEEncodeTiled", "VAEDecodeTiled",
    # FLUX.2 core nodes (current ComfyUI master).
    "EmptyFlux2LatentImage", "Flux2Scheduler",
}

# Curated custom-node class -> (repo_url, friendly_name). Prefixes ending in '*'
# match by startswith (e.g. "easy " catches every ComfyUI-Easy-Use node).
NODE_REPO: dict[str, tuple[str, str]] = {
    # ComfyUI-Impact-Pack
    "FaceDetailer": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "SAMLoader": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "DetailerForEach": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "DetailerForEachDebug": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "BboxDetectorSEGS": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "SegmDetectorSEGS": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "ImpactSimpleDetectorSEGS": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "ImpactSwitch": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "PreviewBridge": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "SEGSPreview": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "MaskToSEGS": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    "EmptySegs": ("https://github.com/ltdrdata/ComfyUI-Impact-Pack.git", "Impact-Pack"),
    # ComfyUI-Impact-Subpack — must be a TOP-LEVEL sibling in custom_nodes/ (not nested inside Impact-Pack)
    "UltralyticsDetectorProvider": ("https://github.com/ltdrdata/ComfyUI-Impact-Subpack.git", "Impact-Subpack"),
    # ComfyUI_IPAdapter_plus
    "IPAdapterAdvanced": ("https://github.com/cubiq/ComfyUI_IPAdapter_plus.git", "IPAdapter_plus"),
    "IPAdapterTiled": ("https://github.com/cubiq/ComfyUI_IPAdapter_plus.git", "IPAdapter_plus"),
    "IPAdapterModelLoader": ("https://github.com/cubiq/ComfyUI_IPAdapter_plus.git", "IPAdapter_plus"),
    "IPAdapterUnifiedLoader": ("https://github.com/cubiq/ComfyUI_IPAdapter_plus.git", "IPAdapter_plus"),
    "IPAdapter": ("https://github.com/cubiq/ComfyUI_IPAdapter_plus.git", "IPAdapter_plus"),
    # ComfyUI-Easy-Use (prefix) — easy imageRemBg, easy loraStackApply, easy showAnything…
    "easy *": ("https://github.com/yolain/ComfyUI-Easy-Use.git", "Easy-Use"),
    # rgthree-comfy — Context / Context Big / Seed / KSampler Config (the Anima
    # All-In-One master workflow routes model+clip+vae+conditioning through these).
    "Context (rgthree)": ("https://github.com/rgthree/rgthree-comfy.git", "rgthree-comfy"),
    "Context Big (rgthree)": ("https://github.com/rgthree/rgthree-comfy.git", "rgthree-comfy"),
    "Seed (rgthree)": ("https://github.com/rgthree/rgthree-comfy.git", "rgthree-comfy"),
    "KSampler Config (rgthree)": ("https://github.com/rgthree/rgthree-comfy.git", "rgthree-comfy"),
    "Image Comparer (rgthree)": ("https://github.com/rgthree/rgthree-comfy.git", "rgthree-comfy"),
    # KJNodes — Get/Set virtual globals, switches, primitives, math, compile patches.
    "GetNode": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "SetNode": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "ComfySwitchNode": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "LazySwitchKJ": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "GetImageSize": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "ImageScaleToTotalPixels": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "PathchSageAttentionKJ": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "TorchCompileModelAdvanced": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "ModelPatchTorchSettings": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "PrimitiveStringMultiline": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "PrimitiveInt": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "PrimitiveFloat": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    "PrimitiveBoolean": ("https://github.com/kijai/ComfyUI-KJNodes.git", "KJNodes"),
    # ComfyMath — ComfyMathExpression
    "ComfyMathExpression": ("https://github.com/evanspearman/ComfyMath.git", "ComfyMath"),
    # WAS Node Suite — StringConcatenate, Masks Combine Batch
    "StringConcatenate": ("https://github.com/WASasquatch/was-node-suite-comfyui.git", "was-node-suite"),
    "Masks Combine Batch": ("https://github.com/WASasquatch/was-node-suite-comfyui.git", "was-node-suite"),
    # pysssss Custom Scripts — ShowText
    "ShowText|pysssss": ("https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git", "pysssss-Custom-Scripts"),
    # ComfyUI-Image-Saver (alexopus) — "Image Saver" + its sampler/scheduler/unet selector nodes.
    # NOT Comfyroll: these "(Image Saver)" classes ship from comfyui-image-saver, which is what the
    # working v13 worker clones. (Mis-mapping them to a Comfyroll fork builds a worker that boots
    # but fails every anima render with `Node 'Image Saver' not found`.)
    "Image Saver": ("https://github.com/alexopus/comfyui-image-saver.git", "Image-Saver"),
    "Sampler Selector (Image Saver)": ("https://github.com/alexopus/comfyui-image-saver.git", "Image-Saver"),
    "Scheduler Selector (Image Saver)": ("https://github.com/alexopus/comfyui-image-saver.git", "Image-Saver"),
    "UNet loader with Name (Image Saver)": ("https://github.com/alexopus/comfyui-image-saver.git", "Image-Saver"),
    # ComfyUI-Lora-Manager — Lora Stacker (the master's preset-style routing point)
    "Lora Stacker (LoraManager)": ("https://github.com/willmiao/ComfyUI-Lora-Manager.git", "Lora-Manager"),
    # ComfyUI-Spectrum-SDXL — SpectrumSDXL sampling-acceleration patch
    "SpectrumSDXL": ("https://github.com/ruwwww/comfyui-spectrum-sdxl.git", "Spectrum-SDXL"),
    # ComfyUI-Spectrum-KSampler — anima DiT sampling patches (verified: both classes are
    # registered in sorryhyun/ComfyUI-Spectrum-KSampler/nodes.py NODE_CLASS_MAPPINGS).
    "AnimaModGuidance": ("https://github.com/sorryhyun/ComfyUI-Spectrum-KSampler.git", "Spectrum-KSampler"),
    "DiTSpectrumPatch": ("https://github.com/sorryhyun/ComfyUI-Spectrum-KSampler.git", "Spectrum-KSampler"),
    # ComfyUI-DCW — DCWModelPatch (verified: namemechan/ComfyUI-DCW/dcw_node.py).
    "DCWModelPatch": ("https://github.com/namemechan/ComfyUI-DCW.git", "DCW"),
    # ComfyUI_UltimateSDUpscale
    "UltimateSDUpscale": ("https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git", "UltimateSDUpscale"),
    # ComfyUI-WanVideoWrapper (Wan 2.x video models) — every WanVideo* class + the T5 loader.
    "WanVideo*": ("https://github.com/kijai/ComfyUI-WanVideoWrapper.git", "WanVideoWrapper"),
    "LoadWanVideoT5TextEncoder": ("https://github.com/kijai/ComfyUI-WanVideoWrapper.git", "WanVideoWrapper"),
    # ComfyUI-VideoHelperSuite — mp4/webm muxing for video output.
    "VHS_VideoCombine": ("https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git", "VideoHelperSuite"),
    # ComfyUI-GGUF — GGUF clip/unet loaders (the FLUX.2 klein q8 text encoder).
    "CLIPLoaderGGUF": ("https://github.com/city96/ComfyUI-GGUF.git", "GGUF"),
    "DualCLIPLoaderGGUF": ("https://github.com/city96/ComfyUI-GGUF.git", "GGUF"),
    "UnetLoaderGGUF": ("https://github.com/city96/ComfyUI-GGUF.git", "GGUF"),
    # NOTE on intentionally-absent packs (left for --online / manual resolution):
    #  - Merge Strings v2 [RvTools] / Lora Stack to String [RvTools]: the
    #    rvage/ComfyUI-RvTools repo is deprecated/removed. These only feed the
    #    prompt-merge chain, which Loom overwrites at injection — off the active path.
    #  - NAIARequestRandomWithOverride: a NovelAI random-artist node
    #    (bedovyy/ComfyUI_NAIDGenerator, needs a NAI account). Off the active path
    #    for local Anima rendering (same prompt-merge branch as RvTools).
    #  - SAM3_Detect: a NATIVE core node in current ComfyUI (no pack needed), NOT
    #    the custom node the ComfyUI-Manager online map wrongly suggests. Requires
    #    the sam3.1 weights under checkpoints/. Guarded in _FORBIDDEN_REPOS so the
    #    online resolver never tries to clone comfyanonymous/ComfyUI for it.
}

# Authoritative map of which (class_type, input_key) pairs actually LOAD a
# model, and the ComfyUI model dir to place each weight under. A value is
# collected as a weight ONLY if its (class, key) is listed here. Keying on the
# pair — not just the key — is what stops phantom fields like UNETLoader's
# stray ckpt_name (UNETLoader only reads unet_name) from dragging a 6.9 GB
# checkpoint onto the volume that nothing actually loads.
LOADER_INPUTS: dict[tuple[str, str], str] = {
    ("CheckpointLoaderSimple", "ckpt_name"): "checkpoints",
    ("CheckpointLoader", "ckpt_name"): "checkpoints",
    ("UNETLoader", "unet_name"): "diffusion_models",
    # Image Saver's UNet variant reads the same input; without this the Anima
    # UNet would be mis-flagged as a phantom weight and never reach the volume.
    ("UNet loader with Name (Image Saver)", "unet_name"): "diffusion_models",
    ("LoraLoader", "lora_name"): "loras",
    ("LoraLoaderModelOnly", "lora_name"): "loras",
    ("VAELoader", "vae_name"): "vae",
    # Modern ComfyUI layout: CLIP weights under text_encoders/ (legacy clip/
    # is an alias); CLIP-vision stays under clip_vision/.
    ("CLIPLoader", "clip_name"): "text_encoders",
    ("DualCLIPLoader", "clip_name1"): "text_encoders",
    ("DualCLIPLoader", "clip_name2"): "text_encoders",
    ("CLIPVisionLoader", "clip_name"): "clip_vision",
    ("ControlNetLoader", "control_net_name"): "controlnet",
    ("UpscaleModelLoader", "model_name"): "upscale_models",
    ("StyleModelLoader", "style_model_name"): "style_models",
    ("IPAdapterModelLoader", "ipadapter_file"): "ipadapter",
    # Impact-Pack / Impact-Subpack auxiliary loaders.
    ("SAMLoader", "model_name"): "sams",
    ("UltralyticsDetectorProvider", "model_name"): "ultralytics",
    # WanVideoWrapper loaders use non-standard filename fields.
    ("WanVideoModelLoader", "model"): "diffusion_models",
    ("LoadWanVideoT5TextEncoder", "model_name"): "text_encoders",
    ("WanVideoVAELoader", "model_name"): "vae",
    ("WanVideoLoraSelect", "lora"): "loras",
    # ComfyUI-GGUF loaders (FLUX.2 klein q8 text encoder).
    ("CLIPLoaderGGUF", "clip_name"): "text_encoders",
    ("DualCLIPLoaderGGUF", "clip_name1"): "text_encoders",
    ("DualCLIPLoaderGGUF", "clip_name2"): "text_encoders",
    ("UnetLoaderGGUF", "unet_name"): "diffusion_models",
}
MODEL_EXTS = (".safetensors", ".ckpt", ".pt", ".pth", ".bin", ".onnx", ".gguf", ".sft")
PLACEHOLDER = "REPLACE_WITH"


def resolve_node(ct: str) -> tuple[str, str] | None:
    if ct in NODE_REPO:
        return NODE_REPO[ct]
    for pat, repo in NODE_REPO.items():
        if pat.endswith("*") and ct.startswith(pat[:-1]):
            return repo
    return None


def model_dir(ct: str, key: str) -> str | None:
    """Dir a weight belongs under, or None if (ct, key) isn't a real loader input."""
    # easy loraStack takes a dynamic count of lora_<N>_name inputs (num_loras);
    # they're all real LoRA files, so key on the pattern rather than every N.
    if ct == "easy loraStack" and key.startswith("lora_") and key.endswith("_name"):
        return "loras"
    return LOADER_INPUTS.get((ct, key))


def preset_lora_refs() -> dict[str, str]:
    """``{loras-relative name: 'loras'}`` for every image-preset LoRA that has a Civitai
    mapping. Image presets inject LoRAs at render time (not in any workflow JSON), so the
    workflow scan misses them — this folds them into the manifest so they reach the volume.
    Self-contained (reads the two config JSONs directly), to keep this script import-light."""
    refs: dict[str, str] = {}
    try:
        cmap = json.loads((ROOT / "configs" / "civitai_loras.json").read_text(encoding="utf-8"))
        presets = json.loads((ROOT / "configs" / "image_presets.json").read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return refs
    default_sub = str(cmap.get("subdir") or "").strip().strip("/")
    by_name = {e["name"]: e for e in cmap.get("loras", []) if e.get("name")}
    needed = {lr.get("name") for p in presets.get("presets", []) if p.get("id") != "none"
              for lr in (p.get("loras") or [])}
    for name in needed:
        ent = by_name.get(name)
        if not ent:
            continue
        fn = ent.get("filename") or f"{name}.safetensors"
        sub = str(ent.get("subdir") or default_sub).strip().strip("/")
        rel = f"{sub}/{fn}" if sub else fn
        refs[rel.replace("\\", "/")] = "loras"
    return refs


# Repos the ComfyUI-Manager online map returns that are NOT real custom-node
# packs — cloning any of these into custom_nodes/ is wrong or harmful. The map
# is community-maintained and carries false positives (e.g. it maps some node
# class names to comfyanonymous/ComfyUI itself). We refuse these on install and
# report them as UNRESOLVED so the real pack is found by hand.
_FORBIDDEN_REPOS = {
    "https://github.com/comfyanonymous/ComfyUI",
    "https://github.com/comfyanonymous/ComfyUI.git",
}


def online_resolve(unknown: set[str]) -> dict[str, str]:
    """Best-effort: map remaining node classes to repos via ComfyUI-Manager's DB.
    Drops the known false-positive repos in _FORBIDDEN_REPOS (they'd clone core
    ComfyUI into custom_nodes, which breaks the install)."""
    import urllib.request
    url = "https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json"
    try:
        data = json.loads(urllib.request.urlopen(url, timeout=30).read())
    except Exception as e:  # noqa: BLE001
        print(f"  [online] could not fetch node map: {e}")
        return {}
    found = {}
    for repo, payload in data.items():
        if repo in _FORBIDDEN_REPOS:
            continue
        classes = payload[0] if isinstance(payload, list) and payload else []
        for ct in unknown:
            if ct in classes:
                found[ct] = repo if repo.endswith(".git") else repo + ".git"
    return found


def _repo_dir_name(repo_url: str) -> str:
    """The custom_nodes/ folder name a repo clones into (last URL segment, no .git)."""
    return repo_url.rsplit("/", 1)[-1].removesuffix(".git")


def install_local(repos: dict[str, str], comfy_base: Path) -> int:
    """Git-clone every resolved custom-node pack into ``<comfy_base>/custom_nodes/``,
    then install each pack's Python requirements. Already-present packs are skipped
    (refreshed with git pull). Returns the number of packs newly installed.

    This is the LOCAL install path (the mirror of the worker Dockerfile): point it
    at your ComfyUI base directory and the Anima All-In-One master workflow's packs
    land where ComfyUI scans them, so the workflow runs without a RunPod round-trip.
    """
    import subprocess
    custom_nodes = comfy_base / "custom_nodes"
    if not custom_nodes.is_dir():
        sys.exit(f"not a ComfyUI base dir (no custom_nodes/ found): {comfy_base}")
    installed = 0
    print(f"\n==> installing {len(repos)} pack(s) into {custom_nodes} ...\n")
    for url in sorted(repos):
        name = _repo_dir_name(url)
        target = custom_nodes / name
        if target.is_dir():
            # Already there — fast-forward so the latest node defs are in place.
            print(f"  ~ {name}: present, pulling latest")
            subprocess.run(["git", "-C", str(target), "pull", "--ff-only"],
                           capture_output=True)
            continue
        print(f"  + {name}: cloning")
        rc = subprocess.run(["git", "clone", "--depth", "1", url, str(target)]).returncode
        if rc != 0:
            print(f"    FAILED to clone {url}")
            continue
        installed += 1
        # Install this pack's Python deps (best-effort; never fatal — a missing
        # optional dep shouldn't abort the whole install).
        req = target / "requirements.txt"
        if req.is_file():
            py = sys.executable
            subprocess.run([py, "-m", "pip", "install", "-r", str(req)],
                           capture_output=True)
    print(f"\nDone. {installed} new pack(s) installed; restart ComfyUI to load them.")
    return installed


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("workflows", nargs="*", help="workflow stems (default: all in workflows/)")
    ap.add_argument("--models-dir", default=DEFAULT_MODELS_DIR)
    ap.add_argument("--base-tag", default="3.6.0-base", help="runpod-worker-comfy base image tag")
    ap.add_argument("--online", action="store_true", help="resolve unknown nodes via ComfyUI-Manager DB")
    ap.add_argument("--install-local", metavar="COMFY_BASE",
                    help=("install the resolved custom-node packs directly into a LOCAL ComfyUI "
                          "install (path to its base dir, the one containing custom_nodes/), "
                          "instead of just writing the worker Dockerfile. Skips packs already "
                          "present. Requires --online to resolve everything (else warns on gaps)."))
    ap.add_argument("--allow-unresolved", action="store_true",
                    help=("with --install-local, proceed even if some nodes have no known repo "
                          "(they're reported but not installed). Use when the unresolved nodes are "
                          "off the active render path or get bypassed by prompt injection."))
    args = ap.parse_args()

    files = ([WORKFLOWS / f"{w}.json" for w in args.workflows] if args.workflows
             else sorted(WORKFLOWS.glob("*.json")))
    files = [f for f in files if f.is_file()]
    if not files:
        sys.exit("no workflow files found")

    models_dir = Path(args.models_dir)
    repos: dict[str, str] = {}            # repo_url -> friendly name
    unresolved: set[str] = set()
    model_refs: dict[str, str] = {}       # forward-slash name -> dir
    ignored: list[str] = []               # looks like a weight but isn't a real loader input
    load_images: set[str] = set()         # baked LoadImage filenames needing an input/ placeholder
    print(f"Scanning {len(files)} workflow(s)...\n")

    for f in files:
        g = json.loads(f.read_text(encoding="utf-8"))
        for n in g.values():
            if not isinstance(n, dict):
                continue
            ct = n.get("class_type")
            if ct and ct not in CORE_NODES:
                hit = resolve_node(ct)
                if hit:
                    repos[hit[0]] = hit[1]
                else:
                    unresolved.add(ct)
            # LoadImage bakes a filename that ComfyUI resolves from input/. Serverless workers
            # boot with an EMPTY input/, and modern ComfyUI hard-validates the file at QUEUE time
            # ("Invalid image file: X" → HTTP 400) even when the node sits in a gated/unused branch.
            # Record the name so we can ship a placeholder; the real image (if any) is injected at
            # render time by the provider, which overwrites this value.
            if ct == "LoadImage":
                img = (n.get("inputs") or {}).get("image")
                if isinstance(img, str) and img.strip():
                    load_images.add(img.strip())
            for k, v in (n.get("inputs") or {}).items():
                if not (isinstance(v, str) and v.lower().endswith(MODEL_EXTS)):
                    continue
                if PLACEHOLDER in v:
                    continue
                d = model_dir(ct, k)
                if d:
                    model_refs[v.replace("\\", "/")] = d
                else:
                    # A weight-looking string on a non-loader input (e.g. a stray
                    # ckpt_name on UNETLoader) — almost certainly a phantom.
                    ignored.append(f"{v}  ({ct}.{k} in {f.name})")

    # Image-preset LoRAs (render-time injected, absent from workflow JSON) → manifest.
    for rel, d in preset_lora_refs().items():
        model_refs.setdefault(rel, d)

    if unresolved and args.online:
        print(f"Resolving {len(unresolved)} unknown node(s) online...")
        for ct, repo in online_resolve(unresolved).items():
            repos[repo] = repo.rsplit("/", 1)[-1].removesuffix(".git")
            unresolved.discard(ct)

    # ---- Dockerfile ----------------------------------------------------------
    clone_block = " && \\\n    ".join(f"git clone --depth 1 {url}" for url in sorted(repos))

    # Placeholder input/ images so baked LoadImage filenames pass ComfyUI's queue-time file
    # validation on a fresh worker (empty input/). The provider overwrites the value with the
    # real reference at render time for the img2img path; for txt2img the node is unused.
    placeholder_block = ""
    if load_images:
        saves = "; ".join(
            f"p=Path('/comfyui/input/{name}'); p.parent.mkdir(parents=True, exist_ok=True); "
            f"Image.new('RGB',(64,64)).save(p)"
            for name in sorted(load_images)
        )
        placeholder_block = (
            "\n# Placeholder LoadImage inputs (see scan): keep modern ComfyUI from 400-ing on a\n"
            "# baked reference filename that isn't present in a fresh worker's empty input/ dir.\n"
            f'RUN python -c "from PIL import Image; from pathlib import Path; {saves}"\n'
        )

    dockerfile = f"""# AUTO-GENERATED by gen_worker.py — do not hand-edit; re-run the generator.
# One image that runs ALL scanned workflows. Custom-node packs: {', '.join(sorted(repos.values()))}.
# Models are NOT baked in — they live on a RunPod network volume (see extra_model_paths.yaml).
ARG BASE_TAG={args.base_tag}
FROM timpietruskyblibla/runpod-worker-comfy:${{BASE_TAG}}

# Update ComfyUI to latest so newer samplers (er_sde, sa_solver, etc.) are available.
# The base image pins a release tag; fetch+checkout master gets us current HEAD.
RUN cd /comfyui && git fetch origin && git checkout origin/master && pip install --no-cache-dir -r requirements.txt

# PyTorch >= 2.7.1. The base ships 2.6.0, but the Anima pipeline's KJNodes
# ModelPatchTorchSettings node probes torch.backends.cuda.matmul.allow_fp16_accumulation
# (added in 2.7.1) and RAISES on older torch — even with the setting disabled — killing every
# render. 2.7.x dropped cu124 wheels, so cu126 is the BAKED DEFAULT (covers Ampere/Ada/Hopper,
# sm_80–sm_90 — the serverless GPU pool). For other GPUs (e.g. Blackwell sm_120) the entrypoint
# adapts at runtime via light-the-torch (see adaptive_start.sh) — installed here, used only when
# the baked build can't run on the actual GPU.
RUN pip install --no-cache-dir torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 \
        --index-url https://download.pytorch.org/whl/cu126 && \
    pip install --no-cache-dir light-the-torch

WORKDIR /comfyui/custom_nodes
# Impact-Subpack MUST be a top-level sibling here (not nested inside ComfyUI-Impact-Pack/).
# ComfyUI only scans the top level of custom_nodes/; nesting it means UltralyticsDetectorProvider
# never registers → 400.
RUN {clone_block}

# Install each pack's Python deps. Do NOT swallow failures (|| true) — a broken
# pip install leaves ComfyUI unable to load the pack → 400.
# Skip sam2 (heavy; not needed by the Anima FaceDetailer path which uses sam_vit_b).
# Replace opencv-python (needs GUI/GTK libs absent in this headless image) with the
# headless variant so cv2 and ultralytics import without libgthread errors.
RUN for d in */ ; do \\
        if [ -f "$d/requirements.txt" ]; then \\
            grep -viE '^(sam2|git\\+https://github.com/facebookresearch/sam2)' "$d/requirements.txt" > /tmp/req.txt || true ; \\
            if [ -s /tmp/req.txt ]; then pip install --no-cache-dir -r /tmp/req.txt ; fi ; \\
        fi ; \\
    done && \\
    pip install --no-cache-dir "ultralytics>=8.0.0" "segment-anything" && \\
    pip uninstall -y opencv-python opencv-python-headless && \\
    pip install --no-cache-dir opencv-python-headless

# SageAttention: a faster fused-attention kernel the Anima model path patches in
# (KJNodes "PathchSageAttentionKJ", sage_attention=auto). The 1.0.6 PyPI wheel is
# pure-Triton — no nvcc/CUDA-toolkit build needed (triton ships in the base image).
# Without this the patch node raises ModuleNotFoundError → ComfyUI rejects the graph
# ("Error queuing workflow: HTTP 400") on every Anima render.
RUN pip install --no-cache-dir sageattention==1.0.6
{placeholder_block}
COPY extra_model_paths.yaml /comfyui/extra_model_paths.yaml

# Adapt PyTorch to the GPU the worker actually lands on (the baked build only covers
# sm_80–sm_90). adaptive_start.sh smoke-tests CUDA and, only if the baked torch can't run,
# reinstalls a matching build via light-the-torch, then hands off to the base /start.sh.
COPY adaptive_start.sh /adaptive_start.sh
RUN chmod +x /adaptive_start.sh
WORKDIR /
CMD ["/adaptive_start.sh"]
"""
    (HERE / "Dockerfile").write_text(dockerfile, encoding="utf-8")

    # ---- adaptive_start.sh (runtime GPU/PyTorch adaptation) ------------------
    (HERE / "adaptive_start.sh").write_text(_ADAPTIVE_START, encoding="utf-8", newline="\n")

    # ---- extra_model_paths.yaml ---------------------------------------------
    dirs = sorted(set(model_refs.values()) | {"checkpoints", "loras", "vae", "embeddings"})
    SPECIAL = {"ultralytics": ["ultralytics_bbox: models/ultralytics/bbox",
                               "ultralytics_segm: models/ultralytics/segm"]}
    lines = ["# AUTO-GENERATED by gen_worker.py.",
             "# ComfyUI in the worker reads all weights from the attached network volume.",
             "runpod_volume:", "  base_path: /runpod-volume/"]
    for d in dirs:
        if d == "ultralytics":
            for s in SPECIAL[d]:
                lines.append(f"  {s}")
        elif d == "sams":
            lines.append("  sams: models/sams")
        else:
            lines.append(f"  {d}: models/{d}")
    (HERE / "extra_model_paths.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- models_manifest.json (only files that exist locally) ----------------
    manifest, missing = [], []
    for name, d in sorted(model_refs.items()):
        local_rel = f"{d}/{name}"
        # ultralytics names already carry bbox/ or segm/ subdir; others are flat under their dir
        local_path = models_dir / Path(local_rel.replace("/", "\\")) if "\\" in str(models_dir) else models_dir / local_rel
        local_path = models_dir.joinpath(*local_rel.split("/"))
        key = f"models/{local_rel}"
        if local_path.is_file():
            manifest.append({"local": local_rel, "key": key, "bytes": local_path.stat().st_size})
        else:
            missing.append(local_rel)
    (HERE / "models_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    # ---- report --------------------------------------------------------------
    total_gb = sum(m["bytes"] for m in manifest) / 1e9
    print(f"\nDockerfile           -> {len(repos)} custom-node repo(s): {', '.join(sorted(repos.values()))}")
    print(f"extra_model_paths    -> dirs: {', '.join(dirs)}")
    print(f"models_manifest.json -> {len(manifest)} files present locally, {total_gb:.1f} GB")
    if missing:
        print(f"\n  MISSING locally ({len(missing)}) — not added to manifest:")
        for m in missing:
            print(f"    - {m}")
    if ignored:
        print(f"\n  IGNORED ({len(ignored)}) — weight-looking value on a non-loader input (likely a phantom, NOT uploaded):")
        for v in ignored:
            print(f"    - {v}")
    if unresolved:
        print(f"\n  UNRESOLVED custom nodes ({len(unresolved)}) — add to NODE_REPO (or re-run with --online):")
        for u in sorted(unresolved):
            print(f"    - {u}")

    if args.install_local:
        # Installing locally needs every pack resolved — force online if anything
        # is still unknown so we don't ship a half-working install.
        if unresolved and not args.online:
            print("\n  --install-local: forcing --online to resolve remaining nodes...")
            for ct, repo in online_resolve(unresolved).items():
                repos[repo] = repo.rsplit("/", 1)[-1].removesuffix(".git")
                unresolved.discard(ct)
        if unresolved:
            msg = (f"\n--install-local: {len(unresolved)} node(s) unresolved (no safe repo): "
                   f"{', '.join(sorted(unresolved))}")
            if args.allow_unresolved:
                print(msg + "\n  (--allow-unresolved) proceeding without them.")
            else:
                sys.exit(msg + "\n  Add them to NODE_REPO, or pass --allow-unresolved to skip them.")
        install_local(repos, Path(args.install_local))
        return

    print("\nNext: build & push the image, then `python runpod/worker/upload_models.py`.")


if __name__ == "__main__":
    main()
