"""AppContext — the former state-bound create_app closures gathered onto one object.

The constructor holds the five pieces of app state (root, store, base_settings, user,
comfy_url) the web layer closed over. Each method below is a verbatim copy of a former
closure, with the mechanical substitutions defined in REFACTOR_CONTRACT.md:
  root -> self.root, store -> self.store, base_settings -> self.base_settings,
  user -> self.user, comfy_url -> self.comfy_url; sibling helper calls -> self.x(...);
  pure helper calls -> the imported service free function;
  `nonlocal base_settings; base_settings = load_settings(root)` -> self.reload_settings().
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import yaml
from fastapi import UploadFile, File  # noqa: F401 — kept for parity; methods don't define routes
from fastapi.responses import JSONResponse

from ..config import load_settings
from ..config.schema import Character, ModelDef, Settings
from ..connections import ConnectionStore  # noqa: F401 — type reference for callers

from .services import config_files
from .services import prompts as _prompts


# Per-role image-workflow overrides. configs/image_roles.json maps each generation role
# (base/style/sprite/scene/chat) to a workflow key; unset roles fall back to today's
# behavior. Read fresh per request (no restart). See GET/POST /api/image-roles.
# The image pipeline is Anima-only, so every role resolves to an anima* workflow
# (see configs/image_roles.json). No role is hard-pinned to a workflow anymore —
# image_roles.json is the single source of truth for role → workflow mapping.
IMAGE_ROLES = ("base", "sprite", "scene", "chat")


def _parse_role_entry(v) -> tuple[str, dict]:
    """Unpack a roles-config value (plain string OR {model, output_variant, …} object).
    Returns (model_key, extra_opts) — extra_opts feeds image_provider as overrides."""
    if isinstance(v, dict):
        return (v.get("model") or "").strip(), {k: vv for k, vv in v.items() if k != "model"}
    return (v or "").strip(), {}
_ROLE_LABELS = {
    "base": "Character base image",
    "sprite": "Outfit / emotion sprites",
    "scene": "Story location backgrounds",
    "chat": "Chat pictures",
}

_IMG_URL_RE = re.compile(r"https?://[^\s\"'<>)]+?\.(?:png|jpe?g|webp|gif)", re.IGNORECASE)


class AppContext:
    """Holds app state and the state-bound helpers the web layer needs."""

    def __init__(self, root: Path, store, base_settings, user, comfy_url: str):
        self.root = root
        self.store = store
        self.base_settings = base_settings
        self.user = user
        self.comfy_url = comfy_url
        # RunPod config for dynamic GPU scaling
        rp = user.runpod if hasattr(user, 'runpod') else None
        self.runpod_config = {
            # Env var wins so the secret can live in .env (gitignored) rather than user.yaml.
            "enabled": rp.enabled if rp else True,
            "api_key": os.environ.get("RUNPOD_API_KEY", "") or (rp.api_key if rp else ""),
            "serverless_endpoint_id": os.environ.get("RUNPOD_ENDPOINT_ID", "") or (rp.serverless_endpoint_id if rp else ""),
            "images_per_instance": rp.images_per_instance if rp else 10,
            "min_instances": rp.min_instances if rp else 1,
            "max_instances": rp.max_instances if rp else 10,
            "template_id": rp.template_id if rp else None,
        }

    def gpu_info(self, refresh: bool = False) -> dict:
        """The local GPU sampled once at runtime (name/vram_gb/compute_cap). Drives
        local-vs-cloud workflow placement; pass refresh=True to re-probe."""
        from ..comfy.hardware import probe_gpu
        return probe_gpu(refresh=refresh)

    def set_runpod_enabled(self, enabled: bool) -> None:
        """Toggle RunPod routing on/off and persist to user.yaml."""
        self.runpod_config["enabled"] = enabled
        user_path = self.root / "user.yaml"
        raw: dict = yaml.safe_load(user_path.read_text(encoding="utf-8")) if user_path.is_file() else {}
        raw.setdefault("runpod", {})["enabled"] = enabled
        user_path.write_text(yaml.safe_dump(raw, allow_unicode=True, sort_keys=False), encoding="utf-8")

    def reload_settings(self) -> None:
        self.base_settings = load_settings(self.root)

    # -- config-loader wrappers ---------------------------------------------
    def load_image_roles(self) -> dict:
        return config_files.load_image_roles(self.root)

    def pose_tags(self, character_key: str | None, emo: str, outfit_id: str | None = None) -> str:
        """Body-language tags for ONE character at an emotion.

        When `outfit_id` is given, checks the outfit's per-outfit `poses` dict first
        (generated by compose_outfit_poses at wardrobe time). Falls back to the character-level
        `pose_prompts` (legacy / manual), then to empty. 'neutral' always returns NEUTRAL_POSE.
        """
        from .services.poses import NEUTRAL_POSE
        if emo == "neutral":
            return NEUTRAL_POSE
        if not character_key:
            return ""
        m = self.portrait_manifest(character_key)
        if outfit_id:
            outfit = next((o for o in (m.get("outfits") or []) if o.get("id") == outfit_id), None)
            if outfit:
                tags = (outfit.get("poses") or {}).get(emo, "")
                if tags:
                    return tags.strip()
        return ((m.get("pose_prompts") or {}).get(emo) or "").strip()

    def pose_framing(self, emo: str) -> str:
        """Camera-crop framing tags (cowboy / full body) for this emotion's shot geometry (global)."""
        from .services.poses import FRAMING_TAGS, resolve_geometry
        return FRAMING_TAGS[resolve_geometry(emo, config_files.load_poses(self.root))["framing"]]

    def pose_latent(self, emo: str) -> tuple[int, int]:
        """The (width, height) latent canvas for this emotion's aspect (global shot geometry)."""
        from .services.poses import ASPECT_DIMS, resolve_geometry
        return ASPECT_DIMS[resolve_geometry(emo, config_files.load_poses(self.root))["aspect"]]

    def load_pose_library(self) -> dict:
        """Curated body-language pose palette (configs/pose_library.json or the built-in default)."""
        return config_files.load_pose_library(self.root)

    def load_story_builder(self) -> dict:
        return config_files.load_story_builder(self.root)

    # -- resolvers ----------------------------------------------------------
    def effective_settings(self) -> Settings:
        """Base models plus a text model for each saved text/image-prompt connection."""
        models = dict(self.base_settings.models)
        for conn in self.store.list("text"):
            models[conn.id] = ModelDef(provider=conn.provider, kind="text", options=conn.to_model_options())
        return Settings(models=models, characters=self.base_settings.characters, pipelines=self.base_settings.pipelines)

    def image_model_items(self) -> list[dict]:
        fams = self.image_families()
        return [{"id": k, "name": k, "family": fams.get(k, "unknown")}
                for k, m in self.base_settings.models.items() if m.kind == "image"]

    def workflow_family(self, model_id: str | None) -> str:
        """The sub-family (illustrious/pony/anima/…) of an image workflow, read from its
        checkpoint/UNet (folder + tensor arch), with a manual override (configs/families.json) keyed
        by the workflow id or the base filename. 'unknown' if unresolved."""
        from ..comfy.family import family_of
        from ..comfy.scan import classify
        md = self.base_settings.models.get(model_id) if model_id else None
        if md is None or md.kind != "image":
            return "unknown"
        base_name, folder = None, None
        wf = md.options.get("workflow")
        try:
            p = self.root / wf if wf else None
            if p and p.is_file():
                for node in json.loads(p.read_text(encoding="utf-8")).values():
                    ct = node.get("class_type") if isinstance(node, dict) else None
                    if ct == "CheckpointLoaderSimple":
                        base_name, folder = node.get("inputs", {}).get("ckpt_name"), "checkpoints"; break
                    if ct in ("UNETLoader", "UnetLoaderGGUF"):
                        base_name, folder = node.get("inputs", {}).get("unet_name"), "diffusion_models"; break
        except Exception:  # noqa: BLE001
            pass
        arch = ""
        bd = self.comfy_base_dir()
        if base_name and bd and folder:
            fp = bd / "models" / folder / base_name.replace("\\", "/")
            if fp.is_file():
                arch = classify(str(fp)).get("arch") or ""
        ov = config_files.load_families(self.root)
        return family_of(base_name, arch=arch or None,
                         override=ov.get(model_id) or (ov.get(base_name) if base_name else None))

    def image_families(self) -> dict:
        """{workflow_id: family} for every image workflow — for grouping the pickers by container."""
        return {k: self.workflow_family(k)
                for k, m in self.base_settings.models.items() if m.kind == "image"}

    def output_prefix_for(self, model_id: str | None, role: str, character: str | None = None) -> str:
        """Organized ComfyUI output path for a render: loom/<family>/<role>/<character|misc>.
        Pass the resolved workflow id the render actually uses."""
        from .services.img_naming import output_prefix
        return output_prefix(self.workflow_family(model_id), role, character)

    def text_provider_for(self, model_sel: str | None, params: dict | None = None,
                          connection: str | None = None):
        """Build a text provider for a model selection: a registered model key, or a model id
        run through a connection. `connection` (a preset's bound connection id) is used when
        given — so different presets can target different providers (including the local Ollama
        connection); otherwise the active text connection. `params` (temperature/top_p/…) are
        merged into the provider options. Local inference is just an Ollama connection now (its
        keyless + no-think quirks ride along via Connection.to_model_options)."""
        from ..providers.registry import build_provider

        params = params or {}
        s = self.effective_settings()
        if model_sel and model_sel in s.models and s.models[model_sel].kind == "text":
            md = s.models[model_sel]
            if params:
                md = md.model_copy(); md.options = {**md.options, **params}
            return build_provider(md)
        conn = (self.store.get(connection) if connection else None) or self.store.active("text")
        if conn:
            opts = conn.to_model_options()          # carries provider quirks (e.g. Ollama keyless + no-think)
            if model_sel:
                opts["model"] = model_sel
            opts.update(params)                     # a config's params win (incl. reasoning_effort)
            return build_provider(ModelDef(provider=conn.provider, kind="text", options=opts))
        return None

    def ip_provider(self):
        """The image-prompt model's text/vision provider (its own connection,
        falling back to the chat connection)."""
        from ..providers.registry import build_provider

        conn = self.store.active("image_prompt") or self.store.active("text")
        if conn is None:
            return None
        return build_provider(ModelDef(provider=conn.provider, kind="text", options=conn.to_model_options()))

    def image_provider(self, model_id: str | None = None, output_variant: str | None = None,
                       provider_override: str | None = None):
        """A provider for an image WORKFLOW — an explicit workflow id if given, else the active
        image connection, plus the resolved model id. (provider, id) or (None, error_message).
        output_variant ('full'|'cutout') overrides whatever the model definition says.

        `provider_override` picks where the workflow runs (a preset's `image_provider`):
          'cloud' → force RunPod serverless · 'local' → force local ComfyUI ·
          '' / None → the global default (configs/runpod_models.json flags it per workflow)."""
        from ..providers.comfyui_provider import ComfyUIProvider

        conn = self.store.active("image")
        model_id = model_id or (conn.model if conn else None) or self.user.defaults.get("image_model")
        md = self.base_settings.models.get(model_id) if model_id else None
        if md is None or md.kind != "image":
            return None, "no image model selected — pick one in ⚙ Models → Image model"
        opts = dict(md.options)
        if output_variant:
            opts["output_variant"] = output_variant

        # Where does this workflow run? Explicit override wins; otherwise the per-workflow
        # global default (runpod_models.json). 'cloud' needs the serverless endpoint + key.
        rp = self.runpod_config
        cloud_ready = bool(rp.get("api_key") and rp.get("serverless_endpoint_id"))
        want_cloud = (provider_override == "cloud") or \
            (provider_override in (None, "") and model_id in self.runpod_models())
        # Hardware fallback: if the caller didn't force a target and this workflow's models
        # aren't installed locally, it literally can't run on this machine — prefer cloud
        # rather than failing on a missing-model error. Probe is cached; guarded so any
        # hiccup falls back to the prior (local) behaviour.
        if not want_cloud and provider_override in (None, "") and cloud_ready:
            try:
                from ..comfy.hardware import estimate_vram_need
                wf_path = self.workflow_path(model_id)
                bd = self.comfy_base_dir()
                if wf_path and wf_path.is_file() and bd:
                    graph = json.loads(wf_path.read_text(encoding="utf-8"))
                    if estimate_vram_need(graph, bd / "models")["missing"]:
                        want_cloud = True
            except Exception:  # noqa: BLE001
                pass
        if want_cloud and cloud_ready:
            from ..providers.runpod_serverless_provider import RunPodServerlessProvider
            ropts = dict(opts)
            ropts["endpoint_id"] = rp["serverless_endpoint_id"]
            ropts["api_key"] = rp["api_key"]
            return RunPodServerlessProvider(ropts), model_id

        if conn and conn.base_url:
            opts["base_url"] = conn.base_url
        opts["flags"] = {**opts.get("flags", {}), **self.image_flags()}
        return ComfyUIProvider(opts), model_id

    def runpod_models(self) -> set[str]:
        """Image-model keys flagged to run on RunPod serverless (configs/runpod_models.json)."""
        from .services import config_files as _cf
        return set(_cf.load_runpod_models(self.root))

    def image_flags(self) -> dict:
        """Global pipeline toggles for renders (configs/app.json) → the workflow's switch
        gates. `img_upscale` drives BOTH the USDU and hi-res upscale branches (the "4K flow")."""
        from .services import config_files as _cf
        f = _cf.load_app_flags(self.root)
        up = bool(f.get("img_upscale", False))
        return {"detailer": bool(f.get("img_detailer", True)), "upscale": up, "highrez": up}

    def role_default(self, role: str) -> str | None:
        """What a role resolves to with NO override: the active image connection's model,
        else the user.yaml default."""
        conn = self.store.active("image")
        return (conn.model if conn else None) or self.user.defaults.get("image_model")

    def role_model(self, role: str, override: str | None = None) -> str | None:
        """Resolve the workflow key for a generation role: explicit override > image_roles.json > default."""
        if override:
            return override
        key, _ = _parse_role_entry(self.load_image_roles().get(role))
        return key if (key and key in self.base_settings.models) else self.role_default(role)

    def role_extra_opts(self, role: str) -> dict:
        """Extra provider options for a role from image_roles.json (e.g. output_variant)."""
        _, opts = _parse_role_entry(self.load_image_roles().get(role))
        return opts

    def role_image_provider(self, role: str, override: str | None = None,
                            image_preset: str | None = None):
        """Convenience: resolve role → (model_key + output_variant) → image provider.
        When override is set the caller chose a model explicitly — skip role extra opts.
        The active (or per-render `image_preset`) LoRA stack is injected before return — the
        single chokepoint every normal render path funnels through.

        Chat-surface roles ('chat'/'scene') take the ACTIVE preset's image WORKFLOW + provider
        (local/cloud) + look — the unified preset bundles them. Pipeline roles (base/sprite/
        style) keep using image_roles.json. Backward-compatible: a preset with no
        image_workflow falls straight through to the legacy role resolution."""
        prov_override = ""
        if not override and role in ("chat", "scene"):
            from .services import presets as _P
            ap = _P.active_preset(self.root)
            if (ap.get("image_workflow") or "") in self.base_settings.models:
                override = ap["image_workflow"]
                prov_override = ap.get("image_provider") or ""
                if image_preset is None and ap.get("image_preset"):
                    image_preset = ap["image_preset"]
        model_id = self.role_model(role, override)
        variant = None if override else self.role_extra_opts(role).get("output_variant")
        provider, mid = self.image_provider(model_id, output_variant=variant,
                                            provider_override=prov_override)
        if provider is not None:
            self._apply_image_preset(provider, image_preset)
        return provider, mid

    def preset_image_provider(self, preset: dict | None, override: str | None = None,
                              output_variant: str | None = None):
        """The unified image entry: a PRESET's image workflow + provider (local/cloud) + look.
        `preset.image_workflow` is the workflow (override wins); `preset.image_provider` routes
        local⇄cloud; `preset.image_preset` is the LoRA stack. Falls back to the active image
        connection when the preset names no workflow. The single chokepoint, same as
        role_image_provider, so the LoRA look is always injected."""
        preset = preset or {}
        workflow = override or (preset.get("image_workflow") or None)
        provider, mid = self.image_provider(
            workflow, output_variant=output_variant,
            provider_override=preset.get("image_provider") or "")
        if provider is not None:
            self._apply_image_preset(provider, preset.get("image_preset") or None)
        return provider, mid

    def _apply_image_preset(self, provider, preset_id: str | None) -> None:
        """Neutralize the workflow's baked LoRA styles, inject the chosen image preset's stack, and
        gather LoRA trigger words → provider.prompt_suffix (appended to the positive conditioning at
        render). Triggers come from BOTH the preset's LoRAs (explicit `trigger` field) AND any LoRAs
        sitting in the workflow's own `easy loraStack` node (resolved from metadata). `preset_id`
        None/"" → the global-default active preset; "none" → vanilla base."""
        from ..comfy.stack import inject_models, neutralize_baked_stack, resolve_lora_names
        from .services import image_presets as IP

        neutralize_baked_stack(provider.workflow)
        pid = preset_id or IP.load_image_presets(self.root).get("active")
        preset = IP.get_image_preset(self.root, pid)

        triggers: list[str] = []
        if preset and preset["id"] != "none" and preset.get("loras"):
            # Presets store LoraManager bare names; map them to real ComfyUI lora filenames.
            loras = resolve_lora_names(list(preset["loras"]), self.available_loras())
            provider.workflow = inject_models(
                provider.workflow, preset.get("base_checkpoint") or None, loras)
            triggers += [t for lr in preset["loras"] if (t := str(lr.get("trigger") or "").strip())]
        # LoRAs added straight to the workflow's easy loraStack node have no trigger field —
        # resolve theirs from each file's metadata so they fire too.
        triggers += self._workflow_lora_triggers(provider.workflow)
        # Trigger words must appear in the prompt to fire — the provider appends them to the
        # positive conditioning (a string suffix, so it works for single-stage AND Gemma-optimized
        # krea2 workflows alike). De-duped, order preserved.
        provider.prompt_suffix = ", ".join(dict.fromkeys(t for t in triggers if t))

    def _workflow_lora_triggers(self, workflow: dict) -> list[str]:
        """Trigger words for LoRAs sitting in the workflow's `easy loraStack` node(s), resolved
        from each LoRA's metadata (Civitai trained words, else the file's own trigger phrase;
        cached by lora_metadata). Skips stacks toggled off and empty slots; never raises."""
        from ..comfy.civitai import lora_metadata, local_trigger_words
        bd = self.comfy_base_dir()
        loras_dir = (bd / "models" / "loras") if bd else None
        out: list[str] = []
        for node in (workflow or {}).values():
            if not isinstance(node, dict) or node.get("class_type") != "easy loraStack":
                continue
            ins = node.get("inputs") or {}
            if ins.get("toggle") is False:          # stack disabled → its LoRAs don't apply
                continue
            try:
                num = min(max(int(ins.get("num_loras") or 10), 0), 10)
            except (TypeError, ValueError):
                num = 10
            for k in range(1, num + 1):
                name = str(ins.get(f"lora_{k}_name") or "").strip()
                if not name or name == "None":
                    continue
                try:
                    tw = (lora_metadata(self.root, name, loras_dir).get("trained_words")
                          or local_trigger_words(loras_dir, name))
                except Exception:                    # noqa: BLE001 — never break a render on lookup
                    tw = None
                if tw:
                    out.append(", ".join(tw) if isinstance(tw, list) else str(tw))
        return out

    _loras_cache: list | None = None

    def available_loras(self) -> list[str]:
        """The ComfyUI LoraLoader filename list (cached per process). Empty if unreachable."""
        if self._loras_cache is not None:
            return self._loras_cache
        loras: list[str] = []
        try:
            import httpx
            r = httpx.get(self.active_comfy_url().rstrip("/") + "/object_info/LoraLoader", timeout=10)
            r.raise_for_status()
            v = (r.json().get("LoraLoader", {}).get("input", {}).get("required", {}).get("lora_name"))
            if isinstance(v, list) and v and isinstance(v[0], list):
                loras = list(v[0])
        except Exception:  # noqa: BLE001
            pass
        self._loras_cache = loras
        return loras

    def allow_nsfw(self) -> bool:
        """The global content gate (configs/app.json). When False, nsfw-rated lorebooks are
        excluded from retrieval everywhere."""
        from .services import config_files as _cf
        return bool(_cf.load_app_flags(self.root).get("allow_nsfw", True))

    def author_provider(self, model_sel: str | None, params: dict | None = None):
        """Text provider for the Story Builder — an explicit (selectable) author
        model if given, else the active chat connection. Always raises the token
        ceiling (a small default truncates a stage's structured JSON). A config's
        `params` (temperature/…) override, so an explicit max_tokens wins over the default."""
        from ..providers.registry import build_provider

        params = params or {}
        s = self.effective_settings()
        if model_sel and model_sel in s.models and s.models[model_sel].kind == "text":
            md = s.models[model_sel].model_copy()
            md.options = {**md.options, "max_tokens": 40000, **params}
            return build_provider(md)
        conn = self.store.active("text")
        if conn is None:
            return None
        opts = {**conn.to_model_options(), "max_tokens": 40000, **params}
        if model_sel:
            opts["model"] = model_sel
        return build_provider(ModelDef(provider=conn.provider, kind="text", options=opts))

    def stage_provider(self, stage: str | None, model_override: str | None = None,
                       max_tokens: int = 40000):
        """The ONE model-resolution chokepoint for a pipeline stage. A STAGE LOREBOOK bound
        to a PRESET supplies the stage's model + connection + params (so any stage can run
        local Ollama, etc., like every chat surface). Falls back to the legacy
        configs/story_builder.json per-stage model. An explicit `model_override` wins.
        Returns a text provider (or None)."""
        from .services import presets as _presets
        if stage and not model_override:
            preset = _presets.stage_preset(self.root, stage)
            if preset:
                params = {"max_tokens": max_tokens, **(preset.get("params") or {})}
                prov = self.text_provider_for(
                    preset.get("model") or None, params,
                    connection=preset.get("connection") or None)
                if prov is not None and hasattr(prov, "generate_text"):
                    return prov
                # preset present but unbuildable → fall through to the legacy config
        cfg = self.load_story_builder()
        return self.author_provider(
            config_files._stage_model(cfg, stage, model_override),
            config_files.stage_params(cfg, stage))

    def stage_system(self, stage: str | None) -> str | None:
        """The stage's SYSTEM prompt from its bound preset (stage lorebook → preset), or None
        to defer to the caller's default / story_builder.json systems."""
        if not stage:
            return None
        from .services import presets as _presets
        preset = _presets.stage_preset(self.root, stage)
        return (preset or {}).get("system") or None

    def builder_ctx(self, body: dict, stage: str | None = None):
        """(provider, systems) for a builder step, or (None, err). The stage's model +
        connection + params + system resolve through the unified stage chokepoint (a stage
        lorebook bound to a preset), falling back to configs/story_builder.json. An explicit
        per-request `body.model` override still wins."""
        cfg = self.load_story_builder()
        systems = dict(cfg.get("systems") or {})
        model_override = (body or {}).get("model")
        if not model_override:
            sys_override = self.stage_system(stage)
            if sys_override:
                systems[stage] = sys_override
        provider = self.stage_provider(stage, model_override)
        if provider is None or not hasattr(provider, "generate_text"):
            return None, "no chat connection — connect a chat model first"
        return provider, systems

    # A thin seed → a thorough, disciplined-prose character sheet. The single "flesh thin→rich" front
    # door that feeds every downstream parser (appearance / pose / expression → tags).
    _FLESH_INSTRUCTION = (
        "Expand this thin seed into a thorough, vivid character: full physical appearance, personality, "
        "demeanor, and how they physically carry and express themselves — while staying faithful to the "
        "details given.")

    def flesh_character(self, key: str, instruction: str = "") -> dict:
        """Rewrite a (thin) character into a thorough disciplined-prose sheet (persona + appearance +
        role) via the story reviser, persisted IN PLACE. Returns the new fields or {error}."""
        from ..stories import revise_character
        ch = self.base_settings.characters.get(key)
        if ch is None:
            return {"error": "no such character"}
        provider, systems = self.builder_ctx({}, "characters")
        if provider is None:
            return {"error": systems}
        fields = ch.fields or {}
        try:
            revised = revise_character(
                provider, name=ch.name, persona=ch.system or "", role=fields.get("role", ""),
                appearance=fields.get("appearance", ""),
                instruction=instruction.strip() or self._FLESH_INSTRUCTION,
                systems=systems)
        except Exception as exc:  # noqa: BLE001
            return {"error": f"flesh failed: {exc}"}
        data = self._read_character_data(key) or {}
        data["name"] = revised.get("name") or data.get("name") or ch.name
        data["system"] = revised.get("persona") or ch.system or ""
        data["fields"] = {**(data.get("fields") or {}), "role": revised.get("role") or fields.get("role", ""),
                          "appearance": revised.get("appearance") or fields.get("appearance", "")}
        self._write_character_data(key, data)   # owning story DB (embedded) or global YAML
        return {"ok": True, "name": data["name"], "persona": data["system"],
                "appearance": data["fields"]["appearance"], "role": data["fields"]["role"]}

    def ensure_fleshed(self, key: str) -> None:
        """Auto-fallback: if a character's persona is still thin (a bare seed), flesh it into the
        disciplined-prose sheet before generation parses tags from it. No-op on thorough personas."""
        ch = self.base_settings.characters.get(key)
        if ch is not None and len((ch.system or "").strip()) < 320:
            self.flesh_character(key)

    def card_extras(self, ch, char_key: str) -> dict:
        fields = ch.fields or {}
        return {"scenario_text": fields.get("scenario"),
                "first_mes": ch.greeting or fields.get("first_mes"),
                "mes_example": fields.get("mes_example"),
                "appearance": fields.get("appearance")}

    def active_comfy_url(self) -> str:
        conn = self.store.active("image")
        return (conn.base_url if conn and conn.base_url else self.comfy_url)

    def comfy_base_dir(self) -> Path | None:
        """The managed ComfyUI base directory (holds models/checkpoints, models/
        loras). None for connect-only setups where we don't know the layout."""
        from ..comfy.server import get_server
        launch = getattr(get_server(self.comfy_url), "launch", None)
        bd = getattr(launch, "base_directory", None) if launch else None
        return Path(bd) if bd else None

    def workflow_path(self, model_key: str) -> Path | None:
        md = self.base_settings.models.get(model_key)
        if md is None or md.kind != "image":
            return None
        wf = md.options.get("workflow")
        if not wf:
            return None
        path = (self.root / wf).resolve()
        # Guard against path traversal — must stay inside the project root.
        if self.root.resolve() not in path.parents:
            return None
        return path

    # -- paths --------------------------------------------------------------
    def char_dir(self) -> Path:
        return self.root / "configs" / "characters"

    def persona_dir(self, *, create: bool = False) -> Path:
        """configs/personas — one YAML per persona (filename stem = key), with a
        <key>.png avatar alongside. Created on demand."""
        d = self.root / "configs" / "personas"
        if create:
            d.mkdir(parents=True, exist_ok=True)
        return d

    def persona_avatar_path(self, key: str) -> Path | None:
        """The persona's avatar PNG (<key>.png), or None if absent."""
        safe = re.sub(r"[^\w\-]+", "", key)
        p = self.persona_dir() / f"{safe}.png"
        return p if p.is_file() else None

    def save_persona_avatar(self, key: str, png: bytes) -> str:
        """Write the chosen portrait candidate's bytes to <key>.png."""
        safe = re.sub(r"[^\w\-]+", "", key)
        self.persona_dir(create=True)
        (self.persona_dir() / f"{safe}.png").write_bytes(png)
        return f"/api/personas/{key}/avatar"

    def write_persona(self, key: str, data: dict) -> dict:
        """Validate + persist a persona YAML (configs/personas/<key>.yaml), then reload.
        `key` is the filename stem; the caller is responsible for slug/dedup."""
        from ..config.schema import Persona
        Persona(**{k: v for k, v in data.items() if k != "key"})  # validate (drops a stray 'key')
        self.persona_dir(create=True)
        payload = {k: v for k, v in data.items() if k in ("name", "description", "summary",
                                                          "appearance", "fields") and v not in (None, "")}
        (self.persona_dir() / f"{key}.yaml").write_text(
            yaml.safe_dump(payload, allow_unicode=True, sort_keys=False), encoding="utf-8")
        self.reload_settings()
        return {"ok": True, "key": key}

    def delete_persona(self, key: str) -> bool:
        """Remove a persona's YAML + avatar PNG, then reload. Returns whether anything was removed."""
        safe = re.sub(r"[^\w\-]+", "", key)
        removed = False
        for fn in (f"{safe}.yaml", f"{safe}.png"):
            p = self.persona_dir() / fn
            if p.is_file():
                p.unlink()
                removed = True
        if removed:
            self.reload_settings()
        return removed

    def story_dir(self) -> Path:
        return self.root / "configs" / "stories"

    def story_bg_dir(self, key: str) -> Path:
        return self.story_dir() / re.sub(r"[^\w\-]+", "", key) / "bg"

    def portrait_dir(self, key: str, *, create: bool = False) -> Path:
        safe = re.sub(r"[^\w\-]+", "", key)
        d = self.root / "configs" / "characters" / "portraits" / safe
        if create:
            d.mkdir(parents=True, exist_ok=True)
        return d

    def portrait_manifest(self, key: str) -> dict:
        p = self.portrait_dir(key) / "manifest.json"
        if p.is_file():
            try:
                return json.loads(p.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001 — corrupt manifest: start fresh
                pass
        return {"appearance": "", "outfits": []}

    def save_portrait_manifest(self, key: str, data: dict) -> None:
        d = self.portrait_dir(key, create=True)
        (d / "manifest.json").write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    def portrait_outfit(self, manifest: dict, oid: str) -> dict | None:
        return next((o for o in manifest.get("outfits", []) if o.get("id") == oid), None)

    def reference_path(self, key: str) -> Path | None:
        """The character's img2img reference image: a dedicated <key>.ref.png if
        set, else the card avatar <key>.png. None if neither exists."""
        safe = re.sub(r"[^\w\-]+", "", key)
        for fn in (f"{safe}.ref.png", f"{safe}.png"):
            p = self.char_dir() / fn
            if p.is_file():
                return p
        return None

    def sets_dir(self) -> Path:
        return self.root / "configs" / "prompt_sets"

    def dataset_dir(self, name: str) -> Path | None:
        safe = re.sub(r"[^\w\-]+", "_", name or "").strip("_")
        d = (self.root / "datasets" / safe).resolve()
        if not safe or self.root.resolve() not in d.parents or not d.is_dir():
            return None
        return d

    # -- domain ops ---------------------------------------------------------
    def character_images(self, k: str, c) -> list[dict]:
        """All images attached to a character, categorized and checked. Local files
        are verified to exist; URLs found in the card are listed as external."""
        char_dir = self.char_dir()
        out: list[dict] = []
        has_avatar = (char_dir / f"{k}.png").is_file()
        has_ref = (char_dir / f"{k}.ref.png").is_file()
        if has_avatar:
            out.append({"kind": "avatar", "url": f"/api/characters/{k}/avatar", "ok": True, "source": "card"})
        # the reference is the dedicated ref if present, else the avatar
        if has_ref or has_avatar:
            out.append({"kind": "reference", "url": f"/api/characters/{k}/reference",
                        "ok": True, "source": "dedicated" if has_ref else "avatar"})
        # image URLs embedded in the card (description, fields…)
        seen = set()
        for blob in (c.system or "", c.greeting or "", json.dumps(c.fields, ensure_ascii=False)):
            for m in _IMG_URL_RE.findall(blob):
                if m not in seen:
                    seen.add(m)
                    out.append({"kind": "card link", "url": m, "ok": None, "source": "external"})
        return out

    def portrait_payload(self, key: str) -> dict:
        """The manifest enriched with served image URLs for the frontend.

        affect.range in the manifest may be either the old format (list of dicts with
        emotion/valence/arousal) or the new format (list of strings). Both are normalised to
        a plain list of keys here; the API response enriches back to [{emotion, valence, arousal}]
        for the frontend carousel and AffectScatter."""
        from .services.emotions import (EMOTION_KEYS, EMOTION_LABELS, EMOTION_COORDS,
                                        NORMAL_KEYS, range_to_display)
        m = self.portrait_manifest(key)
        base = f"/api/characters/{key}/portraits/img"
        canon = m.get("expression_prompts") or {}
        # Normalise affect.range to a list of string keys regardless of stored format.
        raw_range = (m.get("affect") or {}).get("range") if isinstance(m.get("affect"), dict) else None
        if isinstance(raw_range, list) and raw_range:
            if isinstance(raw_range[0], dict):
                # Old format: [{emotion, valence?, arousal?}] → extract keys
                affect_key_list = [e["emotion"] for e in raw_range if e.get("emotion") in EMOTION_KEYS]
            else:
                # New format: [key1, key2, ...]
                affect_key_list = [k for k in raw_range if k in EMOTION_KEYS]
        else:
            affect_key_list = list(NORMAL_KEYS)
        affect_keys = set(affect_key_list)
        # Build display-ready range (sorted by circumplex angle) for carousel + AffectScatter.
        affect_range_display = range_to_display(affect_key_list)
        outfits = []
        for o in m.get("outfits", []):
            oid = o["id"]
            files = o.get("expressions") or {}
            exprs = {emo: f"{base}/{oid}/{fn}" for emo, fn in files.items()}
            out_prompts = o.get("expression_prompts") or {}
            # Per-OUTFIT emotion range (register-specific). Falls back to the character range for
            # outfits authored before per-outfit ranges existed. `in_range` drives the pane's cells.
            o_raw = o.get("range")
            o_keys = ([k for k in o_raw if k in EMOTION_KEYS]
                      if isinstance(o_raw, list) and o_raw else affect_key_list)
            o_keyset = set(o_keys)
            expression_set = [{
                "emotion": k, "label": EMOTION_LABELS.get(k, k),
                "prompt": out_prompts.get(k) or canon.get(k, ""),
                "url": f"{base}/{oid}/{files[k]}" if files.get(k) else None,
                "valence": EMOTION_COORDS[k][0],
                "arousal": EMOTION_COORDS[k][1],
                "in_range": k in o_keyset,
            } for k in EMOTION_KEYS]
            outfits.append({
                "id": oid, "name": o.get("name") or oid,
                "instruction": o.get("instruction", ""), "prompt": o.get("prompt", ""),
                "attire_prompt": o.get("attire_prompt", o.get("prompt", "")),
                "base": f"{base}/{oid}/base.png" if (o.get("base")) else None,
                "expressions": exprs,
                "expression_set": expression_set,
                "range": o_keys,   # this outfit's register-specific emotion set (keys)
            })
        return {"appearance": m.get("appearance", ""),
                "emotions": EMOTION_KEYS,
                "affect": {"range": affect_range_display, "keys": affect_key_list,
                           "dimensions": ["valence", "arousal"]},
                "expression_prompts": canon, "outfits": outfits}

    def write_npc(self, npc: dict, story_key: str = "", ref_from: str | None = None,
                  base_prompt: str = "") -> str:
        """Create a story-bound Character file (a generated NPC, or the duplicated
        protagonist); returns its key. Tagged with its owning `story` so it's scoped /
        grouped and hidden from global pickers. If `ref_from` is given, that character's
        reference image is copied across. `base_prompt` (from the shared ✨ composer) is stored
        as fields.base_prompt so the base image renders richly without a manual ✨ pass."""
        from ..stories import story_db as SDB
        char_dir = self.char_dir()
        char_dir.mkdir(parents=True, exist_ok=True)
        db = self._story_db(story_key) if story_key else None   # embed into a DB-backed story
        taken = {p.stem for p in char_dir.glob("*.yaml")}
        if db is not None:
            taken |= set(SDB.character_keys(db))
        base = re.sub(r"[^a-z0-9]+", "_", (npc.get("name") or "npc").lower()).strip("_") or "npc"
        key, i = base, 2
        while key in taken:
            key, i = f"{base}_{i}", i + 1
        fields = {"appearance": npc.get("appearance", ""), "role": npc.get("role", ""),
                  "story": story_key, "_generated": True}
        if base_prompt:
            fields["base_prompt"] = base_prompt
        # The portable core harness (relationship-first genesis) lives on the card — see GENESIS.md.
        for hk in ("want", "lie", "wound", "secret"):
            if npc.get(hk):
                fields[hk] = npc[hk]
        try:                                              # numeric stature → sprite scaling (not a tag)
            if npc.get("height_cm"):
                fields["height_cm"] = int(npc["height_cm"])
        except (TypeError, ValueError):
            pass
        cdata = {
            "name": npc.get("name") or key,
            "system": npc.get("persona") or "",
            "fields": fields,
            "_migrated_split": True,
        }
        Character(**cdata)  # validate (extra top-level keys ignored)
        if db is not None:
            SDB.upsert_character(db, key, cdata)   # embedded in the story DB (authoritative)
        else:
            (char_dir / f"{key}.yaml").write_text(
                yaml.safe_dump(cdata, allow_unicode=True, sort_keys=False), encoding="utf-8")
        if ref_from:
            ref = self.reference_path(ref_from)
            if ref and ref.is_file():
                import shutil
                try:
                    shutil.copyfile(ref, char_dir / f"{key}.ref.png")
                except Exception:  # noqa: BLE001
                    pass
        return key

    def write_character(self, cdata: dict, avatar_png: bytes | None) -> dict:
        """Validate + persist a normalized character: one configs/characters/
        <key>.yaml, the avatar PNG alongside (loader globs *.yaml, so the .png is
        ignored by config loading), then reload settings so it's selectable."""
        Character(**cdata)  # raises on a malformed card
        char_dir = self.char_dir()
        char_dir.mkdir(parents=True, exist_ok=True)
        base = re.sub(r"[^a-z0-9]+", "_", cdata["name"].lower()).strip("_") or "character"
        key, i = base, 2
        while (char_dir / f"{key}.yaml").exists():
            key, i = f"{base}_{i}", i + 1
        (char_dir / f"{key}.yaml").write_text(
            yaml.safe_dump(cdata, allow_unicode=True, sort_keys=False), encoding="utf-8")
        if avatar_png and avatar_png.startswith(b"\x89PNG\r\n\x1a\n"):
            (char_dir / f"{key}.png").write_bytes(avatar_png)
        self.reload_settings()
        return {"ok": True, "key": key, "name": cdata["name"],
                "avatar": (char_dir / f"{key}.png").is_file()}

    def prune_orphan_characters(self) -> list[str]:
        """Auto-delete GENERATED characters that no longer belong to any story — their owning
        story was deleted, or they were never cast. Library / imported cards (not `_generated`)
        are NEVER touched; they're independent. Removes the yaml + avatar/ref + portraits, like
        delete_character. Idempotent — safe to call after any story/cast change or at startup.
        Returns the keys removed."""
        import shutil
        live_stories = set(self.base_settings.stories.keys())
        cast_members = {m.character for st in self.base_settings.stories.values() for m in st.cast}
        cdir = self.char_dir()
        removed: list[str] = []
        for k, c in list(self.base_settings.characters.items()):
            fields = c.fields or {}
            if not fields.get("_generated"):
                continue  # a library card — keep it regardless of story membership
            story_key = fields.get("story")
            has_story = (bool(story_key) and story_key in live_stories) or (k in cast_members)
            if has_story:
                continue
            safe = re.sub(r"[^\w\-]+", "", k)
            for fn in (f"{safe}.yaml", f"{safe}.png", f"{safe}.ref.png"):
                fp = cdir / fn
                if fp.is_file():
                    fp.unlink()
            shutil.rmtree(self.portrait_dir(k), ignore_errors=True)
            removed.append(k)
        if removed:
            self.reload_settings()
        return removed

    def save_location_bg(self, key: str, loc: str, png: bytes) -> str:
        """Write a chosen background and record it on the story's location."""
        d = self.story_bg_dir(key); d.mkdir(parents=True, exist_ok=True)
        (d / f"{loc}.png").write_bytes(png)
        data = self._read_story_data(key)
        for l in data.get("locations", []):
            if l.get("id") == loc:
                l["background"] = f"/api/stories/{key}/bg/{loc}.png"
        self._write_story_data(key, data)
        return f"/api/stories/{key}/bg/{loc}.png"

    # ── Persistence routing ── A story is DB-backed iff its <key>.db exists (else legacy YAML). A
    # character is owned by a story DB iff embedded there (authoritative), else it's a global YAML
    # card. These helpers hide the split so every read/write path is store-agnostic. See story_db.py.
    def _story_db(self, key: str):
        from ..stories import story_db as SDB
        safe = re.sub(r"[^\w\-]+", "", key)
        p = self.story_dir() / f"{safe}.db"
        return p if SDB.exists(p) else None

    def _read_story_data(self, key: str) -> dict:
        from ..stories import story_db as SDB
        db = self._story_db(key)
        if db is None:
            raise FileNotFoundError(key)
        story, _chars = SDB.load_story(db)
        return story

    def _write_story_data(self, key: str, data: dict) -> None:
        """Validate + persist a whole story dict to its DB, keeping the embedded characters."""
        from ..config.schema import Story
        from ..stories import story_db as SDB
        Story(**data)   # validate FIRST — never persist a corrupt story
        db = self._story_db(key)
        if db is None:
            raise FileNotFoundError(key)
        _story, chars = SDB.load_story(db)
        SDB.save_story(db, data, chars)
        self.reload_settings()

    def create_story(self, name: str, fields: dict, character_keys=None, type_: str = "novel") -> str:
        """Mint a NEW story as its own ``<skey>.db``, EMBEDDING the records of any referenced
        characters (the file is the whole self-contained story). Derives a unique key from `name`,
        validates, reloads. Returns the key. The single creation chokepoint (genesis_commit + the
        cast/wizard saves route here). See stories/story_db.py."""
        from ..config.schema import Story
        from ..stories import story_db as SDB
        existing = {st.name for st in self.base_settings.stories.values()}
        nm, j = name.strip() or "Story", 2
        while nm in existing:
            nm, j = f"{(name.strip() or 'Story')} ({j})", j + 1
        base = re.sub(r"[^\w\-]+", "_", nm.lower()).strip("_") or "story"
        sdir = self.story_dir(); sdir.mkdir(parents=True, exist_ok=True)
        skey, i = base, 2
        while (sdir / f"{skey}.yaml").is_file() or (sdir / f"{skey}.db").is_file():
            skey, i = f"{base}_{i}", i + 1
        chars: dict = {}
        for ck in (character_keys or []):
            rec = self._read_character_data(ck)
            if rec is not None:
                chars[ck] = rec                       # embed the referenced character's record
        story = {"name": nm, "type": type_ if type_ in ("novel", "vn") else "novel", **(fields or {})}
        Story(**story)                                # validate before writing
        SDB.save_story(sdir / f"{skey}.db", story, chars)
        self.reload_settings()
        return skey

    def _char_owner(self, char_key: str) -> str | None:
        """The story key that OWNS this character (embeds it), or None for a global library card."""
        from ..stories import story_db as SDB
        for skey in self.base_settings.stories:
            db = self._story_db(skey)
            if db is not None and char_key in SDB.character_keys(db):
                return skey
        return None

    def _read_character_data(self, key: str) -> dict | None:
        from ..stories import story_db as SDB
        owner = self._char_owner(key)
        if owner is not None:
            return SDB.get_character(self._story_db(owner), key)
        safe = re.sub(r"[^\w\-]+", "", key)
        path = self.char_dir() / f"{safe}.yaml"
        return (yaml.safe_load(path.read_text(encoding="utf-8")) or {}) if path.is_file() else None

    def _write_character_data(self, key: str, cdata: dict) -> None:
        """Persist a character to its OWNING story DB (embedded) or the global YAML library."""
        from ..config.schema import Character
        from ..stories import story_db as SDB
        Character(**cdata)   # validate FIRST
        owner = self._char_owner(key)
        if owner is not None:
            SDB.upsert_character(self._story_db(owner), key, cdata)
        else:
            safe = re.sub(r"[^\w\-]+", "", key)
            (self.char_dir() / f"{safe}.yaml").write_text(
                yaml.safe_dump(cdata, allow_unicode=True, sort_keys=False), encoding="utf-8")
        self.reload_settings()

    def update_story_fields(self, key: str, fields: dict) -> None:
        """Patch top-level fields onto a saved story (DB-backed or legacy YAML) + reload. VALIDATES
        the merged story BEFORE writing. Raises FileNotFoundError for a draft (neither DB nor YAML)."""
        data = self._read_story_data(key)
        data.update(fields)
        # Self-heal a DANGLING start: if it points at a location that no longer exists, drop it —
        # otherwise the whole-Story validator would block every unrelated edit (e.g. adding a location).
        loc_ids = {l.get("id") for l in (data.get("locations") or []) if isinstance(l, dict)}
        if data.get("start") and data["start"] not in loc_ids:
            data["start"] = None
        self._write_story_data(key, data)

    def persist_character_entry(self, key: str, doc: dict) -> None:
        """Persist one character's conversational field edits (the agent's `character:<key>` target).
        `doc` is a {cast:[entry]} artifact the agent mutated; the entry maps back onto the Character
        YAML (persona→system; role/appearance/base_prompt + the core harness onto fields). Only
        non-empty fields are written (so a wardrobe/no-op turn never blanks anything). Validates
        before writing; raises FileNotFoundError for an unknown character."""
        cast = [c for c in (doc.get("cast") or []) if isinstance(c, dict)]
        entry = next((c for c in cast if str(c.get("id")) == key), None) or (cast[0] if cast else None)
        if entry is None:
            raise ValueError("no character entry to persist")
        data = self._read_character_data(key)   # from the owning story DB or the global library
        if data is None:
            raise FileNotFoundError(key)
        if entry.get("name"):
            data["name"] = entry["name"]
        if entry.get("persona"):
            data["system"] = entry["persona"]
        fields = dict(data.get("fields") or {})
        for k in ("role", "appearance", "base_prompt", "temperament", "want", "lie", "wound", "secret"):
            if entry.get(k):
                fields[k] = entry[k]
        data["fields"] = fields
        self._write_character_data(key, data)   # routes back to the same store

    def cast_doc_to_members(self, cast_list) -> list[dict]:
        """Convert an inline cast doc ({name,role,persona,primary}) into Story CastMember refs
        ({character,primary,outfit?}), CREATING a character card for any member that isn't
        already a reference. Idempotent by name — an existing character of the same name is
        reused, never duplicated — and each member is stamped with its resolved `character`
        key so a re-persist won't create a second card. This is how the cast tools persist:
        authoring an inline character actually mints a card via write_character."""
        members: list[dict] = []
        for c in cast_list or []:
            if not isinstance(c, dict):
                continue
            key = (c.get("character") or "").strip()
            if not key:
                name = (c.get("name") or "").strip()
                if not name:
                    continue
                key = next((k for k, ch in self.base_settings.characters.items()
                            if (getattr(ch, "name", "") or "").strip().lower() == name.lower()), "")
                if not key:   # mint a new card from the inline persona
                    res = self.write_character(
                        {"name": name, "system": c.get("persona") or "",
                         "fields": {"role": c.get("role") or ""}}, None)
                    key = (res or {}).get("key", "") if isinstance(res, dict) else ""
                c["character"] = key   # stamp it back so the doc becomes a reference (idempotent)
            if key:
                m = {"character": key, "primary": bool(c.get("primary"))}
                if c.get("outfit"):
                    m["outfit"] = c["outfit"]
                members.append(m)
        return members

    def save_story_bg(self, key: str, png: bytes) -> str:
        """Write a story's COVER image and record it as the story background. Mirrors
        save_location_bg but for the whole-story cover (served at /api/stories/{key}/bg/_cover.png)."""
        d = self.story_bg_dir(key); d.mkdir(parents=True, exist_ok=True)
        (d / "_cover.png").write_bytes(png)
        url = f"/api/stories/{key}/bg/_cover.png"
        self.update_story_fields(key, {"background": url})
        return url

