"""Application context facade.

The facade owns shared process state; focused mixins own provider selection and file-backed persistence. Its public API remains stable for existing routers and jobs.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import yaml
from fastapi import UploadFile, File  # noqa: F401 — kept for parity; methods don't define routes
from fastapi.responses import JSONResponse

from ..config import load_settings
from ..config.schema import Character, ModelDef, Settings
from ..connections import ConnectionStore  # noqa: F401 — type reference for callers

from .services import config_files
from .services import prompts as _prompts



from .context_providers import (IMAGE_ROLES, ProviderContextMixin, _ROLE_LABELS, _parse_role_entry)
from .context_storage import StorageContextMixin, _self_heal_refs


class AppContext(ProviderContextMixin, StorageContextMixin):

    """Holds app state and the state-bound helpers the web layer needs."""

    def __init__(self, root: Path, store, base_settings, user, comfy_url: str):
        self.root = root
        self.store = store
        self.base_settings = base_settings
        self.user = user
        self.comfy_url = comfy_url
        # RunPod config for dynamic GPU scaling
        rp = user.runpod if hasattr(user, 'runpod') else None
        self.runpod_config = {
            # Env var wins so the secret can live in .env (gitignored) rather than user.yaml.
            "enabled": rp.enabled if rp else True,
            "api_key": os.environ.get("RUNPOD_API_KEY", "") or (rp.api_key if rp else ""),
            "serverless_endpoint_id": os.environ.get("RUNPOD_ENDPOINT_ID", "") or (rp.serverless_endpoint_id if rp else ""),
            "min_instances": rp.min_instances if rp else 0,
            "max_instances": rp.max_instances if rp else 2,
            "idle_timeout_s": rp.idle_timeout_s if rp else 5,
            "queue_delay_s": rp.queue_delay_s if rp else 4,
            "template_id": rp.template_id if rp else None,
        }

    def gpu_info(self, refresh: bool = False) -> dict:
        """The local GPU sampled once at runtime (name/vram_gb/compute_cap). Drives
        local-vs-cloud workflow placement; pass refresh=True to re-probe."""
        from ..comfy.hardware import probe_gpu
        return probe_gpu(refresh=refresh)

    def set_runpod_enabled(self, enabled: bool) -> None:
        """Toggle RunPod routing on/off and persist to user.yaml."""
        self.update_runpod_settings(enabled=enabled)

    def update_runpod_settings(self, **changes) -> None:
        """Persist non-secret RunPod settings and keep the live context in sync."""
        allowed = {"enabled", "min_instances", "max_instances", "idle_timeout_s", "queue_delay_s"}
        changes = {key: value for key, value in changes.items() if key in allowed}
        self.runpod_config.update(changes)
        user_path = self.root / "user.yaml"
        raw: dict = yaml.safe_load(user_path.read_text(encoding="utf-8")) if user_path.is_file() else {}
        raw.setdefault("runpod", {}).update(changes)
        user_path.write_text(yaml.safe_dump(raw, allow_unicode=True, sort_keys=False), encoding="utf-8")

    def reload_settings(self) -> None:
        self.base_settings = load_settings(self.root)

    # -- config-loader wrappers ---------------------------------------------
    def load_image_roles(self) -> dict:
        return config_files.load_image_roles(self.root)

    def pose_tags(self, character_key: str | None, emo: str, outfit_id: str | None = None) -> str:
        """Body-language tags for ONE character at an emotion.

        When `outfit_id` is given, checks the outfit's per-outfit `poses` dict first
        (generated by compose_outfit_poses at wardrobe time). Falls back to the character-level
        `pose_prompts` (legacy / manual), then to empty. 'neutral' always returns NEUTRAL_POSE.
        """
        from .services.poses import NEUTRAL_POSE
        if emo == "neutral":
            return NEUTRAL_POSE
        if not character_key:
            return ""
        m = self.portrait_manifest(character_key)
        if outfit_id:
            outfit = next((o for o in (m.get("outfits") or []) if o.get("id") == outfit_id), None)
            if outfit:
                tags = (outfit.get("poses") or {}).get(emo, "")
                if tags:
                    return tags.strip()
        return ((m.get("pose_prompts") or {}).get(emo) or "").strip()

    def pose_framing(self, emo: str) -> str:
        """Camera-crop framing tags (cowboy / full body) for this emotion's shot geometry (global)."""
        from .services.poses import FRAMING_TAGS, resolve_geometry
        return FRAMING_TAGS[resolve_geometry(emo, config_files.load_poses(self.root))["framing"]]

    def pose_latent(self, emo: str) -> tuple[int, int]:
        """The (width, height) latent canvas for this emotion's aspect (global shot geometry)."""
        from .services.poses import ASPECT_DIMS, resolve_geometry
        return ASPECT_DIMS[resolve_geometry(emo, config_files.load_poses(self.root))["aspect"]]

    def load_pose_library(self) -> dict:
        """Curated body-language pose palette (configs/pose_library.json or the built-in default)."""
        return config_files.load_pose_library(self.root)

    def load_story_builder(self) -> dict:
        return config_files.load_story_builder(self.root)

    # -- resolvers ----------------------------------------------------------
    def effective_settings(self) -> Settings:
        """Base models plus a text model for each saved text/image-prompt connection."""
        models = dict(self.base_settings.models)
        for conn in self.store.list("text"):
            models[conn.id] = ModelDef(provider=conn.provider, kind="text", options=conn.to_model_options())
        return Settings(models=models, characters=self.base_settings.characters, pipelines=self.base_settings.pipelines)

