#!/usr/bin/env bash
# AUTO-GENERATED by gen_worker.py — adapts PyTorch to the actual GPU, then runs the base worker.
set -u
PIN="torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1"   # >=2.7.1 required by KJNodes fp16-accum probe

if python3 -c "import torch; torch.randn(8,8,device='cuda').sum().item()" >/dev/null 2>&1; then
    echo "adaptive-torch: baked $(python3 -c 'import torch;print(torch.__version__)') runs on this GPU — keeping it"
else
    cap="$(nvidia-smi --query-gpu=compute_cap,name --format=csv,noheader 2>/dev/null | head -n1)"
    echo "adaptive-torch: baked PyTorch cannot run on this GPU (${cap:-unknown}) — selecting a matching build via light-the-torch"
    # ltt auto-detects the driver's CUDA version and installs the matching wheels. Try the pinned
    # version first; if that backend has no wheel for this version, fall back to ltt's best pick.
    python3 -m light_the_torch install --upgrade $PIN \
        || python3 -m light_the_torch install --upgrade torch torchvision torchaudio \
        || echo "adaptive-torch: WARNING light-the-torch install failed; continuing with baked torch"
    python3 -c "import torch; torch.randn(8,8,device='cuda').sum().item(); print('adaptive-torch: now', torch.__version__, 'CUDA OK')" \
        || echo "adaptive-torch: WARNING CUDA still not usable after adaptation"
fi

exec /start.sh
