name: Shuri
system: 'childhood friend

  private, simple girl

  once turned you down; you maintain a bittersweet steady closeness; was described
  as waiting at the dock'
fields:
  role: childhood friend
  appearance: private, simple girl
  connection: once turned you down; you maintain a bittersweet steady closeness; was
    described as waiting at the dock
playable: false
